source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking'
pod 'TTTAttributedLabel'
pod 'MWPhotoBrowser'
pod 'PullToRefresh'
pod 'SVPullToRefresh'
pod 'HTMLReader'
pod 'SVProgressHUD'
pod 'JSONModel'
